// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"context"
	"github.com/jackc/pgx/v5/pgxpool"
	"log/slog"
	"mzhn/fileservice/internal/config"
	"mzhn/fileservice/internal/providers/uuid"
	"mzhn/fileservice/internal/services/fileservice"
	"mzhn/fileservice/internal/storage/fs"
	"mzhn/fileservice/internal/storage/pg/filerepository"
	"mzhn/fileservice/internal/transport/http"
	"mzhn/fileservice/pkg/sl"
	"time"
)

// Injectors from wire.go:

func New() (*App, func(), error) {
	configConfig := config.New()
	fileStorage := fs.New(configConfig)
	context := _context()
	pool, cleanup, err := _pgxpool(context, configConfig)
	if err != nil {
		return nil, nil, err
	}
	repository := filerepository.New(pool)
	uuidProvider := uuid.New()
	fileService := fileservice.New(fileStorage, fileStorage, repository, uuidProvider)
	v := _servers(configConfig, fileService)
	app := newApp(configConfig, v)
	return app, func() {
		cleanup()
	}, nil
}

// wire.go:

func _servers(cfg *config.Config, fs2 *fileservice.FileService) []Server {
	servers := make([]Server, 0, 2)

	if cfg.Http.Enabled {
		servers = append(servers, http.New(cfg, fs2))
	}

	return servers
}

func _context() context.Context {
	return context.Background()
}

func _pgxpool(ctx context.Context, cfg *config.Config) (*pgxpool.Pool, func(), error) {
	fn := "_pgxpool"
	log := slog.With(slog.String("injector", fn))

	cs := cfg.PG.String()

	pool, err := pgxpool.New(ctx, cs)
	if err != nil {
		return nil, nil, err
	}

	start := time.Now()
	if err := pool.Ping(ctx); err != nil {
		return nil, nil, err
	}
	log.Info("connected to postgres", sl.Millis("took", time.Since(start)))

	return pool, func() {
		pool.Close()
	}, nil

}
